{"uuid": "73c4f872-e1bc-4431-ba6f-88fae3a8802a", "children": ["50c12496-bedc-4e87-a886-00913715fa8d"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_134.0.6998\n", "trace": "  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\conftest.py\", line 17, in browser\n    driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)\n                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\chrome.py\", line 39, in install\n    driver_path = self._get_driver_path(self.driver)\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\manager.py\", line 30, in _get_driver_path\n    file = self._download_manager.download_file(driver.get_driver_download_url())\n                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py\", line 40, in get_driver_download_url\n    driver_version_to_download = self.get_driver_version_to_download()\n                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\driver.py\", line 51, in get_driver_version_to_download\n    self._driver_to_download_version = self._version if self._version not in (None, \"latest\") else self.get_latest_release_version()\n                                                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\drivers\\chrome.py\", line 62, in get_latest_release_version\n    resp = self._http_client.get(url=latest_release_url)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 37, in get\n    self.validate_response(resp)\n  File \"C:\\try\\DemoPytestAllure\\.venv\\Lib\\site-packages\\webdriver_manager\\core\\http.py\", line 16, in validate_response\n    raise ValueError(f\"There is no such driver by url {resp.url}\")\n"}, "start": 1743466657781, "stop": 1743466658399}], "start": 1743466657781, "stop": 1743466658406}